### PR TITLE
add test to validate parameters

### PR DESCRIPTION
**Pull request by AgnieszkaKurek**

### CODE REVIEW

**Review by Krzysiek102 — CHANGES_REQUESTED** [review]
I have no idea how this function goes with what you should do here:
"Write a JavaScript function that accepts a string as a parameter and find the longest word within the string. "
Why do you want to use validateNumber function here?
Are you sure you do what you should do?

**Comment by AgnieszkaKurek** [comment]
Chciałam najpierw zrobić validację

**Comment by AgnieszkaKurek** [comment]
I wanted first make a validation

**Comment by Krzysiek102** [comment]
But validation of what? Will this validation help you in the current task?
Maybe you think about different task then this one:
"Write a JavaScript function that accepts a string as a parameter and find the longest word within the string. "

**Pull request closed without merging**
